# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-01-31 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geo_video_url', models.URLField()),
                ('flag_friday_video_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
