# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_friday_video_url',
            field=models.URLField(null=True),
        ),
    ]
